---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: bar-deployment
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster/namespaces/bar
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: bar-deployment
  validation: none
